import { ResponseParseError } from "./errors.js";

export type HttpMethod = "GET" | "HEAD" | "POST" | "PUT" | "DELETE";

export type QueryValue = string | number | boolean | undefined;

export type QueryInit = {
  q?: string | undefined;
  sort?: string | undefined;
  page?: number | undefined;
  pagelen?: number | undefined;
  /** Raw, unencoded projection. Encoding is `URLSearchParams`' job — see below. */
  fields?: string | undefined;
} & Record<string, QueryValue>;

export type RequestSpec = {
  method?: HttpMethod;
  /** A path under the API root, or an absolute URL (only ever a `next` link). */
  path: string;
  query?: QueryInit;
  body?: unknown;
  accept?: "json" | "text";
  headers?: Readonly<Record<string, string>>;
  signal?: AbortSignal;
  timeoutMs?: number;
  /**
   * Assert that replaying this non-GET is safe. 429 is retried regardless, because a
   * throttled request was rejected rather than processed.
   */
  idempotent?: boolean;
};

/**
 * The single place a query string is constructed.
 *
 * This is what makes Bitbucket's `fields=+reviewers` syntax work. `URLSearchParams`
 * percent-encodes a literal `+` in a value to `%2B`; hand-concatenation does not, and an
 * unencoded `+` decodes server-side to a space, which silently matches no field and
 * returns an unprojected response. Nothing else in this codebase may build a `?`.
 */
export const buildUrl = (spec: RequestSpec, baseUrl: string): string => {
  const isAbsolute = /^https?:\/\//i.test(spec.path);
  const url = isAbsolute
    ? new URL(spec.path)
    : new URL(`${baseUrl.replace(/\/$/, "")}/${spec.path.replace(/^\//, "")}`);

  for (const [key, value] of Object.entries(spec.query ?? {})) {
    if (value !== undefined) {
      url.searchParams.set(key, String(value));
    }
  }
  return url.toString();
};

/**
 * `next` is generated by the server and may carry an opaque cursor, so it is followed
 * verbatim. This only guards against being redirected off-host by a malformed response.
 */
export const assertSameOrigin = (url: string, baseUrl: string): string => {
  const parsed = new URL(url);
  if (parsed.origin !== new URL(baseUrl).origin) {
    throw new ResponseParseError(`Refusing to follow a pagination link to ${parsed.origin}`);
  }
  return url;
};
